name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:1 .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/myimage:1

      - name: Deploy to VPS using SSH keys
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRIVATE_IP }}
          username: ${{ secrets.SSH_PRIVATE_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on error
            docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:1
            docker run -d --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/myimage:1

      

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_PRIVATE_IP }} >> ~/.ssh/known_hosts

      - name: Install Node.js
        run: |
          ssh -o StrictHostKeyChecking=no vouchee@171.235.242.225 "curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt install -y nodejs"

      - name: Deploy to Server
        run: |
          scp -r ./* ${{ secrets.SSH_PRIVATE_NAME }}@${{ secrets.SSH_PRIVATE_IP }}:/var/www/Vouchee_SE/
          ssh ${{ secrets.SSH_PRIVATE_NAME }}@${{ secrets.SSH_PRIVATE_IP }} "cd /var/www/Vouchee_SE && npm install && pm2 restart all"
 
