name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:1 .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/myimage:1

  pull_images:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job
    steps:
      - name: Pull Docker images
        run: |
          docker pull nginx
          docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:1

  run_images:
    runs-on: ubuntu-latest
    needs: pull_images  # Ensure this job runs after the pull_images job
    steps:
      - name: Run Docker images
        run: |
          docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -q)
          docker run -d -p 10000:80 nginx
          docker run -d -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/myimage:1  # Change 5000 to your desired port

  deploy:
    runs-on: ubuntu-latest
    needs: run_images  # Ensure this job runs after the run_images job
    steps:
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_PRIVATE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_PRIVATE_NAME }}@${{ secrets.SSH_PRIVATE_IP }} "cd /var/www/Vouchee_SE && git pull"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_PRIVATE_NAME }}@${{ secrets.SSH_PRIVATE_IP }} "docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -q)" 
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_PRIVATE_NAME }}@${{ secrets.SSH_PRIVATE_IP }} "docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:1 && docker run -d --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/myimage:1" 
