name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
      
    - name: Setup .NET  
      uses: actions/setup-dotnet@v2  
      with:  
        dotnet-version: '7.0.x'  

    - name: Restore dependencies  
      run: dotnet restore  

    - name: Build  
      run: dotnet build --configuration Release --no-restore  

    - name: Test  
      run: dotnet test --no-build --verbosity normal  

    - name: Build Docker image  
      run: docker build -t myimage .  

    - name: Push Docker image  
      run: |  
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin  
        docker push myimage  

    - name: Deploy to VPS  
      run: |  
        ssh Notch272@86436392 'docker pull myimage && docker run -d myimage'
